### ISSUE TITLE
DAZE EULA 위반 사람 발견

### ISSUE THREAD

**Issue by ParkChanSol** [organization/DAZE-EULA#1]
@HmHmmHm hm님 제가 권고해놨으니 내리지 않는다면 hm님이 처리 바라겠습니다

위반 게시물 : http://blog.naver.com/mzlamzla11/220815013656
사진 등 증거물 : http://blog.naver.com/sorisem4106/220828066131

**Comment by ParkChanSol** [comment]
@UzinSG 유진님, hm님 대신 봐주세요

**Comment by UzinSG** [comment]
@ParkChanSol 카카오톡 Sch3023 연락 바랍니다.

**Comment by ParkChanSol** [comment]
@UzinSG 죄송하지만, 카톡이 안되는 관계입니다(그거 아니였으면 오가닉 벌써 들어갔습니다)
